##---------------------------------#
#      general configuration      #
#---------------------------------#
image: Visual Studio 2019
branches:
  except:
    - gh-pages

environment:
  COVERALLS_REPO_TOKEN:
    secure: Pn67B/ELnBY8YWJUBE4s4oIx98wS5NRLTOrP7AP/EiuU2l9brndSCF2cPL6+JUBe
  NUGET_API_KEY:
    secure: cJV4lINlVi8J4NOZBAS5GnaaugKWWO0Zi5jCSKfkDOgs5mEpPDjIf9K0D8hB4bTU

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --target Publish
 
test: off

artifacts:
  - path: artifacts/coverage.xml
  - path: artifacts/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: y4qyCzCMLVH/DEwqh0WpXYryveAR7kuSSe25yd3PlLJms3dw7rB2gJpYc7HKW37y
  artifact: nuget
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true
